# Generated by Django 4.2.7 on 2025-08-28 18:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_ticker', models.CharField(help_text='Stock ticker symbol (e.g., AAPL, GOOGL)', max_length=10)),
                ('stock_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current stock price', max_digits=10, null=True)),
                ('email', models.EmailField(help_text='Email address for stock notifications', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('last_price_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('scheduled', 'Scheduled Notification'), ('manual', 'Manual Send'), ('price_alert', 'Price Alert')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('bounced', 'Email Bounced')], default='pending', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('email_to', models.EmailField(max_length=254)),
                ('stock_price_at_send', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='subscriptions.stocksubscription')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocksubscription',
            index=models.Index(fields=['user', 'is_active'], name='stock_subsc_user_id_636d01_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksubscription',
            index=models.Index(fields=['stock_ticker'], name='stock_subsc_stock_t_ba6edc_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksubscription',
            index=models.Index(fields=['created_at'], name='stock_subsc_created_0fd165_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocksubscription',
            constraint=models.UniqueConstraint(fields=('user', 'stock_ticker', 'email'), name='unique_user_stock_email'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['subscription', 'created_at'], name='notificatio_subscri_d0e3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='notificatio_status_95b675_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_0cc56e_idx'),
        ),
    ]
